# Stubs for neomodel.cardinality (Python 3)
#

from neomodel.relationship_manager import RelationshipManager
from typing import Any, Optional


class ZeroOrOne(RelationshipManager):
    description: str = ...
    def single(self): ...
    def all(self): ...
    def connect(self, node: Any, properties: Optional[Any] = ...): ...


class OneOrMore(RelationshipManager):
    description: str = ...
    def single(self): ...
    def all(self): ...
    def disconnect(self, node: Any): ...


class One(RelationshipManager):
    description: str = ...
    def single(self): ...
    def all(self): ...
    def disconnect(self, node: Any) -> None: ...
    def disconnect_all(self) -> None: ...
    def connect(self, node: Any, properties: Optional[Any] = ...): ...
