# Stubs for neomodel.config (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

AUTO_INSTALL_LABELS: bool
DATABASE_URL: str
FORCE_TIMEZONE: bool
ENCRYPTED_CONNECTION: bool
MAX_POOL_SIZE: int
