# Stubs for neomodel.exceptions (Python 3)

from typing import Any, Optional


class NeomodelException(Exception): ...
class AttemptedCardinalityViolation(NeomodelException): ...

class CardinalityViolation(NeomodelException):
    rel_manager: Any = ...
    actual: Any = ...
    def __init__(self, rel_manager: Any, actual: Any) -> None: ...

class ModelDefinitionException(NeomodelException):
    db_node_class: Any = ...
    current_node_class_registry: Any = ...
    def __init__(
        self, db_node_class: Any, current_node_class_registry: Any
    ) -> None: ...

class ModelDefinitionMismatch(ModelDefinitionException): ...
class ClassAlreadyDefined(ModelDefinitionException): ...

class ConstraintValidationFailed(ValueError, NeomodelException):
    message: Any = ...
    def __init__(self, msg: str) -> None: ...

class DeflateError(ValueError, NeomodelException):
    property_name: str = ...
    node_class: Any = ...
    msg: str = ...
    obj: Any = ...
    def __init__(self, key: str, cls: Any, msg: str, obj: Any) -> None: ...

class DoesNotExist(NeomodelException):
    message: str = ...
    def __init__(self, msg: str) -> None: ...
    def __reduce__(self): ...

class InflateConflict(NeomodelException):
    cls_name: str = ...
    property_name: str = ...
    value: Any = ...
    nid: Any = ...
    def __init__(self, cls: Any, key: str, value: Any, nid: Any) -> None: ...

class InflateError(ValueError, NeomodelException):
    property_name: str = ...
    node_class: Any = ...
    msg: str = ...
    obj: Any = ...
    def __init__(
        self, key: str, cls: Any, msg: str, obj: Optional[Any] = ...
    ) -> None: ...

class DeflateConflict(InflateConflict):
    cls_name: str = ...
    property_name: str = ...
    value: Any = ...
    nid: Any = ...
    def __init__(self, cls: Any, key: str, value: Any, nid: Any) -> None: ...

class MultipleNodesReturned(ValueError, NeomodelException):
    message: str = ...
    def __init__(self, msg: str) -> None: ...

class NotConnected(NeomodelException):
    action: Any = ...
    node1: Any = ...
    node2: Any = ...
    def __init__(self, action: Any, node1: Any, node2: Any) -> None: ...

class RequiredProperty(NeomodelException):
    property_name: str = ...
    node_class: Any = ...
    def __init__(self, key: str, cls: Any) -> None: ...

class UniqueProperty(ConstraintValidationFailed):
    message: str = ...
    def __init__(self, msg: str) -> None: ...
