# Stubs for neomodel.util (Python 3)

from threading import local
from typing import (Any, Callable, Generic, List, Optional, Tuple, Type,
                    TypeVar, cast)

from .exceptions import (ConstraintValidationFailed, ModelDefinitionMismatch,
                         UniqueProperty)
from .match import NodeSet

logger: Any

def ensure_connection(func: Any): ...
def change_neo4j_password(db: Any, new_password: Any) -> None: ...
def clear_neo4j_database(db: Any) -> None: ...

class NodeClassRegistry:
    def __init__(self) -> None: ...

class Database(local, NodeClassRegistry):
    url: str = ...
    driver: Any = ...
    def __init__(self) -> None: ...
    def set_connection(self, url: Any) -> None: ...
    @property
    def transaction(self): ...
    @property
    def write_transaction(self): ...
    @property
    def read_transaction(self): ...
    def begin(self, access_mode: Optional[Any] = ...) -> None: ...
    def commit(self): ...
    def rollback(self) -> None: ...
    def cypher_query(
        self,
        query: str,
        params: Optional[Any] = ...,
        handle_unique: bool = ...,
        retry_on_session_expire: bool = ...,
        resolve_objects: bool = ...,
    ) -> Tuple[List[List[Any]], Any]: ...

class TransactionProxy:
    db: Any = ...
    access_mode: Any = ...
    def __init__(self, db: Any, access_mode: Optional[Any] = ...) -> None: ...
    def __enter__(self): ...
    def __exit__(self, exc_type: Any, exc_value: Any, traceback: Any) -> None: ...
    def __call__(self, func: Any): ...

def deprecated(message: Any): ...

T = TypeVar("T")

# TODO: there seems to be a bug in mypy that prevents this pattern from working
# see https://github.com/python/mypy/issues/2563
def classproperty(f: Callable[[Type[T]], NodeSet[T]]) -> NodeSet[T]:
    class cpf(Generic[T]):
        def __init__(self, getter: Callable[[Type[T]], NodeSet[T]]) -> None: ...
        def __get__(self, obj: Any, type: Type[T]) -> NodeSet[T]: ...
    return cpf(f)

class _UnsavedNode: ...

def _get_node_properties(node: Any) -> Any: ...
